import {solveEnclosure,enclosurePower,solveChain} from './calc.mjs';
const $=id=>document.getElementById(id), enc=document.body.classList.contains('enclosure');
const SLUG=enc?'enclosure-thermal':'thermal-chain', KEY=SLUG+'-inputs-v1';
const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—', escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let latest=null,params=null,layers=[{name:'TIM 導熱介面',t:.2,k:3,w:20,h:20}],deferred;
function getNum(id,lo=-Infinity,hi=Infinity){const el=$(id),s=el.value.trim(),n=Number(s);if(!s||!Number.isFinite(n)||n<lo||n>hi){el.setAttribute('aria-invalid','true');throw Error(`${el.closest('label').querySelector('span').textContent.trim()}：請填入 ${lo} 到 ${hi} 之間的有效數值。`);}el.removeAttribute('aria-invalid');return n;}
function read(){
 if(enc)return {L:getNum('L',1,10000)/1000,W:getNum('W',1,10000)/1000,H:getNum('H',1,10000)/1000,Q:getNum('Q',0,1e6),Ta:getNum('Ta',-20,120),Tr:getNum('Tr',-20,120),limit:getNum('limit',-20,250),eps:getNum('eps',0,1),bottom:$('bottom').checked,mode:$('mode').value,h:$('mode').value==='manual'?getNum('h',.01,1000):5};
 const ls=[...$('layers').querySelectorAll('.layer')].map((row,i)=>({name:row.querySelector('[data-key=name]').value.trim()||`材料層 ${i+1}`,t:getNum('t-'+i,.001,1000),k:getNum('k-'+i,.001,10000),w:getNum('w-'+i,.001,10000),h:getNum('height-'+i,.001,10000)}));layers=ls;
 return {P:getNum('P',0,1e6),Tplate:getNum('Tplate',-100,300),max:getNum('max',-100,500),Rjc:getNum('Rjc',0,10000),contact:getNum('contact',0,10000),spread:getNum('spread',0,10000),parallel:$('parallel').checked,Rother:$('parallel').checked?getNum('Rother',.001,1e6):20,Ta:$('parallel').checked?getNum('Ta',-100,300):25,path:$('path').value,layers:ls};
}
function restore(){try{const obj=JSON.parse(localStorage.getItem(KEY)||'null');if(!obj)return;for(const [id,value]of Object.entries(obj.fields||{})){const el=$(id);if(el){if(el.type==='checkbox')el.checked=!!value;else el.value=value;}}if(!enc&&Array.isArray(obj.layers)&&obj.layers.length<=12)layers=obj.layers;}catch{}}
function save(){try{const fields={};document.querySelectorAll('form input[id],form select[id]').forEach(el=>{if(!el.closest('.layer'))fields[el.id]=el.type==='checkbox'?el.checked:el.value;});localStorage.setItem(KEY,JSON.stringify({fields,layers}));}catch{}}
function renderLayers(){
 $('layers').innerHTML=layers.map((l,i)=>`<div class="layer"><div class="layer-head"><span>材料層 ${i+1}</span><button class="remove" data-remove="${i}" type="button" aria-label="刪除材料層 ${i+1}">移除</button></div><label class="field"><span>材料名稱</span><input data-key="name" value="${escape(l.name)}" maxlength="50"></label><div class="fields" style="margin-top:12px">${[['t','厚度','mm',l.t],['k','導熱係數','W/(m·K)',l.k],['w','有效寬度','mm',l.w],['height','有效長度','mm',l.h]].map(([id,title,unit,value])=>`<label class="field"><span>${title} <em class="unit">${unit}</em></span><input id="${id}-${i}" data-key="${id==='height'?'h':id}" type="number" step="any" min="0.001" value="${value}"></label>`).join('')}</div></div>`).join('');
}
function syncLayers(){layers=[...$('layers').querySelectorAll('.layer')].map(row=>Object.fromEntries([...row.querySelectorAll('input[data-key]')].map(el=>[el.dataset.key,el.dataset.key==='name'?el.value:(el.value===''?'':Number(el.value))])));}
function visibility(){if(enc){$('manualh').classList.toggle('hidden',$('mode').value!=='manual');}else $('other-path').classList.toggle('hidden',!$('parallel').checked);}
function graph(xs,ys,ref,current,xlabel,ylabel,color){
 const W=560,H=250,l=56,r=18,t=22,b=43;
 const xmin=xs[0],xmax=xs.at(-1),ymin=Math.min(0,...ys,ref), ymax=Math.max(...ys,ref,1)*1.08;
 const x=v=>l+(v-xmin)/(xmax-xmin)*(W-l-r),y=v=>H-b-(v-ymin)/(ymax-ymin)*(H-t-b);
 const ticks=Array.from({length:5},(_,i)=>{const v=ymin+(ymax-ymin)*i/4;return `<line x1="${l}" x2="${W-r}" y1="${y(v)}" y2="${y(v)}" stroke="#e2eaf0"/><text x="${l-8}" y="${y(v)+4}" text-anchor="end" fill="#60778a" font-size="11">${fmt(v,0)}</text>`;}).join('');
 const d=xs.map((v,i)=>`${i?'L':'M'}${x(v).toFixed(2)},${y(ys[i]).toFixed(2)}`).join(' ');
 const dot=current&&current.x>=xmin&&current.x<=xmax?`<circle cx="${x(current.x)}" cy="${y(current.y)}" r="5" fill="${color}" stroke="white" stroke-width="2"/>`:'';
 return `<svg class="chart" role="img" aria-label="${escape(xlabel+'對'+ylabel+'關係；橘色虛線表示'+(enc?'目前熱負載':'接面溫度上限'))}" viewBox="0 0 ${W} ${H}">${ticks}<text x="${l}" y="12" fill="#60778a" font-size="11">${ylabel}</text><line x1="${l}" x2="${W-r}" y1="${y(ref)}" y2="${y(ref)}" stroke="#d77934" stroke-dasharray="5 5"/><path d="${d}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/>${dot}${[xmin,(xmin+xmax)/2,xmax].map(v=>`<text x="${x(v)}" y="${H-b+20}" fill="#60778a" text-anchor="middle" font-size="11">${fmt(v,0)}</text>`).join('')}<text x="${W/2}" y="${H-5}" text-anchor="middle" fill="#60778a" font-size="11">${xlabel}</text></svg>`;
}
function renderEnclosure(p,r){
 const good=r.Ts<=p.limit,margin=p.limit-r.Ts;
 const pct=p.Q>0?r.qc/p.Q*100:0;
 $('result').innerHTML=`<section class="result"><h2>預估外殼平均溫度</h2><div class="big">${fmt(r.Ts)} <span class="unit">°C</span></div><p class="sub">相對空氣溫升 ${fmt(r.Ts-p.Ta)} K · 有效散熱面積 ${fmt(r.A,3)} m²</p><span class="status ${good?'':'bad'}">${good?'低於':'超過'}外殼設定上限 ${fmt(Math.abs(margin))} °C</span><div class="metrics"><div><span>自然對流${p.mode==='manual'?'（自訂 h）':''}</span><b>${fmt(r.qc)} W</b></div><div><span>淨輻射散熱</span><b>${fmt(r.qr)} W</b></div><div><span>上限時散熱能力</span><b>${fmt(r.capacity)} W</b></div></div></section>`;
 $('face-table').innerHTML=`<table><thead><tr><th>表面</th><th>面積 m²</th><th>h W/m²K</th><th>對流 W</th><th>輻射 W</th></tr></thead><tbody>${r.faces.map(f=>`<tr><td>${f.name}${f.A===0?'（略去）':''}</td><td>${fmt(f.A,3)}</td><td>${f.A?fmt(f.h,2):'—'}</td><td>${fmt(f.qc)}</td><td>${fmt(f.qr)}</td></tr>`).join('')}</tbody></table>`;
 let notes=[];const invalid=r.faces.filter(f=>f.A>0&&!f.valid);if(invalid.length)notes.push('以下表面的自然對流關係式超出建議範圍，結果包含外推：'+invalid.map(f=>`${f.name}（Ra=${f.Ra.toExponential(2)}；${f.range}）`).join('、')+'。');if(!r.filmValid)notes.push('空氣膜溫超出 250–500 K，空氣性質近似的可信度降低。');if(r.qc<0||r.qr<0)notes.push('負散熱量代表該環境正在向箱體供熱，淨散熱仍需滿足能量平衡。');
 $('warnings').innerHTML=`<div class="note">外殼平均溫度不代表元件溫度。${p.Q>0&&r.qc>=0&&r.qr>=0?`目前對流占 ${fmt(pct,0)}%，輻射占 ${fmt(100-pct,0)}%。`:''}能量平衡：${fmt(r.qc+r.qr,2)} W = 輸入 ${fmt(p.Q,2)} W。</div>`+notes.map(n=>`<div class="note warn">${n}</div>`).join('');
 const min=Math.min(p.Ta,p.Tr),max=Math.max(p.limit+10,r.Ts+15,min+30),xs=Array.from({length:61},(_,i)=>min+(max-min)*i/60);$('chart').innerHTML=graph(xs,xs.map(T=>enclosurePower(p,T)),p.Q,{x:r.Ts,y:p.Q},'外殼溫度 °C','散熱量 W','#087f87');
}
function renderChain(p,r){
 $('result').innerHTML=`<section class="result"><h2>預估接面溫度 Tj</h2><div class="big">${fmt(r.Tj)} <span class="unit">°C</span></div><p class="sub">${p.parallel?'雙路徑熱網路':'單一冷板散熱路徑'} · ${p.path==='top'?'頂面':'底面'}冷卻</p><span class="status ${r.margin>=0?'':'bad'}">${r.margin>=0?'距離':'超過'}接面設定上限 ${fmt(Math.abs(r.margin))} °C</span><div class="metrics"><div><span>冷板路徑熱阻</span><b>${fmt(r.R,3)} K/W</b></div><div><span>封裝接觸面</span><b>${fmt(r.caseT)} °C</b></div><div><span>允許冷板溫度</span><b>${fmt(r.maxPlate)} °C</b></div></div></section>`;
 $('stages').innerHTML=r.nodes.map((n,i)=>`<div class="stage"><div class="stage-dot">${i+1}</div><div class="stage-info">${escape(n.name)}<br><span>${fmt(n.R,3)} K/W · ${fmt(n.R/r.R*100,0)}% · ${fmt(n.high)} → ${fmt(n.low)} °C</span><div class="stage-bar"><div style="width:${n.R/r.R*100}%"></div></div></div><b>${fmt(n.drop)} K</b></div>`).join('')+`<div class="note">流向冷板 ${fmt(r.Qcold,2)} W${p.parallel?`；另一支路 ${fmt(r.Qother,2)} W`:''}。合計 ${fmt(r.Qcold+r.Qother,2)} W = 元件損耗 ${fmt(p.P,2)} W。</div>`;
 let notes=[];if(r.Qcold<-.001||r.Qother<-.001)notes.push('存在反向熱流：負值表示該路徑向接面供熱。請核對兩個邊界溫度。');if(!p.parallel)notes.push('此估算假設全部損耗流向冷板；有顯著 PCB 散熱時，可加入獨立並聯支路。');if(r.maxPlate>300||r.maxPlate<-100)notes.push('允許冷板溫度超出本工具的輸入範圍；它是理想熱網路的代數值，不能直接視為可行運轉條件。');$('warnings').innerHTML=notes.map(n=>`<div class="note ${r.Qcold<0?'warn':''}">${n}</div>`).join('');
 const min=p.Tplate-20,max=Math.max(p.Tplate+30,Math.min(p.Tplate+60,r.maxPlate+10)),xs=Array.from({length:41},(_,i)=>min+(max-min)*i/40);$('chart').innerHTML=graph(xs,xs.map(T=>solveChain({...p,Tplate:T}).Tj),p.max,{x:p.Tplate,y:r.Tj},'冷板接觸面溫度 °C','接面溫度 °C','#5654b7');
}
function update(){visibility();try{const p=read(),r=enc?solveEnclosure(p):solveChain(p);if(!Number.isFinite(enc?r.Ts:r.Tj))throw Error('輸入造成無效結果，請檢查數值。');params=p;latest=r;$('error').textContent='';$('result').hidden=false;if(enc)renderEnclosure(p,r);else renderChain(p,r);save();}catch(e){latest=null;$('error').textContent=e.message;$('result').hidden=true;for(const id of enc?['chart','face-table','warnings']:['chart','stages','warnings'])$(id).innerHTML='';}}
restore();if(!enc)renderLayers();visibility();update();
$('form').addEventListener('submit',e=>{e.preventDefault();update();});
let timer;$('form').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(update,250);});
$('form').addEventListener('change',e=>{if(enc&&e.target.id==='finish'&&e.target.value!=='custom')$('eps').value=e.target.value;if(enc&&e.target.id==='eps')$('finish').value='custom';update();});
$('reset').addEventListener('click',()=>{try{localStorage.removeItem(KEY);}catch{}$('form').reset();if(!enc){layers=[{name:'TIM 導熱介面',t:.2,k:3,w:20,h:20}];renderLayers();}update();});
if(!enc){$('add').addEventListener('click',()=>{if(layers.length>=12){$('error').textContent='最多可加入 12 個材料層。';return;}syncLayers();layers.push({name:'材料層 '+(layers.length+1),t:.1,k:5,w:20,h:20});renderLayers();update();});$('layers').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){syncLayers();layers.splice(Number(b.dataset.remove),1);renderLayers();update();}});}
$('export').addEventListener('click',()=>{update();if(!latest)return;const text=JSON.stringify({tool:document.title,version:'1.0',timestamp:new Date().toISOString(),units:'尺寸：m（箱體）／mm（材料）；功率：W；溫度：°C；熱阻：K/W；導熱係數：W/(m·K)',inputs:params,results:latest},null,2);const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=SLUG+'-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;});$('install').addEventListener('click',async()=>{if(deferred){await deferred.prompt();deferred=null;}else $('install-help').showModal();});$('close-help').addEventListener('click',()=>$('install-help').close());
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
