import assert from 'node:assert/strict';
import {parsePoints,interpolate,quadraticFit,intersections,calculate,FLOW,PRESSURE} from './calc.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8*Math.max(1,Math.abs(b)),`${a} != ${b}`);
assert.deepEqual(parsePoints('Flow (CFM),Pressure (Pa)\n"1","2"\n"0","3"'),[{q:0,p:3},{q:1,p:2}]);
assert.throws(()=>parsePoints('0,1\n1,'));assert.throws(()=>parsePoints('0,1\n0,2'));
assert.throws(()=>parsePoints('0,1\n2,-1'));
assert.equal(interpolate([{q:0,p:1},{q:1,p:0}],2),null);
close(quadraticFit([{q:0,p:0},{q:1,p:3},{q:2,p:12}]).k,3);
const fan=[{q:0,p:100},{q:1,p:0}];
close(intersections(fan,q=>100*q*q,[0,1])[0].q,(Math.sqrt(5)-1)/2);
close(intersections(fan,q=>200*q*q,[0,1])[0].q,.5);
assert.equal(intersections(fan,q=>100*q*q,[0,1])[0].stable,true);
assert.equal(intersections(fan,q=>200,[0,1]).length,0);
const multi=intersections([{q:0,p:3},{q:1,p:0},{q:2,p:3},{q:3,p:0}],q=>1,[0,3]);assert.equal(multi.length,3);assert.equal(multi[1].stable,false);
const tangent=intersections([{q:0,p:1},{q:2,p:1}],q=>1+(q-1)**2,[0,2]);assert.equal(tangent.length,1);close(tangent[0].q,1);
const base={fanFlow:'m3/s',fanPressure:'Pa',filterFlow:'m3/s',filterPressure:'Pa',displayFlow:'m3/s',displayPressure:'Pa',fanText:'0,100\n1,0',filterText:'0,0\n1,100',count:'1',speed:'100',dirty:'2',width:'1000',height:'1000',reference:'1',extra:'0',method:'quadratic',arrangement:'parallel'};
let r=calculate(base);close(r.roots[0].q,(Math.sqrt(5)-1)/2);close(r.dirtyRoots[0].q,.5);
r=calculate({...base,count:'2'});close(r.fan.at(-1).q,2);close(r.fan[0].p,100);
r=calculate({...base,count:'2',arrangement:'series'});close(r.fan.at(-1).q,1);close(r.fan[0].p,200);
r=calculate({...base,speed:'50'});close(r.fan.at(-1).q,.5);close(r.fan[0].p,25);
r=calculate({...base,filterFlow:'m/s',width:'500',height:'200'});close(r.filter.at(-1).q,.1);
const inCfm=calculate({...base,fanFlow:'CFM',fanText:`0,100\n${1/FLOW.CFM},0`,filterPressure:'mmH2O',filterText:`0,0\n1,${100/PRESSURE.mmH2O}`});close(inCfm.roots[0].q,calculate(base).roots[0].q);
assert.throws(()=>calculate({...base,speed:''}));
const limited=calculate({...base,method:'interpolation',filterText:'0,0\n0.1,1'});assert.equal(limited.roots.length,0);
console.log('Passed: parsing, duplicates, units, face velocity, fitting, intersections, tangent/multiple roots, fan array/speed, range limits.');
