import assert from 'node:assert/strict';
import {parsePoints,interpolate,quadraticFit,intersections,calculate,FLOW,PRESSURE} from './calc.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8*Math.max(1,Math.abs(b)),`${a} != ${b}`);
assert.deepEqual(parsePoints('Flow (CFM),Pressure (Pa)\n"1","2"\n"0","3"'),[{q:0,p:3},{q:1,p:2}]);
assert.throws(()=>parsePoints('0,1\n1,'));assert.throws(()=>parsePoints('0,1\n0,2'));
assert.throws(()=>parsePoints('0,1\n2,-1'));
assert.equal(interpolate([{q:0,p:1},{q:1,p:0}],2),null);
close(quadraticFit([{q:0,p:0},{q:1,p:3},{q:2,p:12}]).k,3);
const fan=[{q:0,p:100},{q:1,p:0}];
close(intersections(fan,q=>100*q*q,[0,1])[0].q,(Math.sqrt(5)-1)/2);
close(intersections(fan,q=>200*q*q,[0,1])[0].q,.5);
assert.equal(intersections(fan,q=>100*q*q,[0,1])[0].stable,true);
assert.equal(intersections(fan,q=>200,[0,1]).length,0);
const multi=intersections([{q:0,p:3},{q:1,p:0},{q:2,p:3},{q:3,p:0}],q=>1,[0,3]);assert.equal(multi.length,3);assert.equal(multi[1].stable,false);
const tangent=intersections([{q:0,p:1},{q:2,p:1}],q=>1+(q-1)**2,[0,2]);assert.equal(tangent.length,1);close(tangent[0].q,1);
const base={fanFlow:'m3/s',fanPressure:'Pa',filterFlow:'m3/s',filterPressure:'Pa',displayFlow:'m3/s',displayPressure:'Pa',fanText:'0,100\n1,0',filterText:'0,0\n1,100',count:'1',speed:'100',dirty:'2',width:'1000',height:'1000',reference:'1',extra:'0',method:'quadratic',arrangement:'parallel'};
let r=calculate(base);close(r.roots[0].q,(Math.sqrt(5)-1)/2);close(r.dirtyRoots[0].q,.5);
r=calculate({...base,count:'2'});close(r.fan.at(-1).q,2);close(r.fan[0].p,100);
r=calculate({...base,count:'2',arrangement:'series'});close(r.fan.at(-1).q,1);close(r.fan[0].p,200);
r=calculate({...base,speed:'50'});close(r.fan.at(-1).q,.5);close(r.fan[0].p,25);
r=calculate({...base,filterFlow:'m/s',width:'500',height:'200'});close(r.filter.at(-1).q,.1);
const inCfm=calculate({...base,fanFlow:'CFM',fanText:`0,100\n${1/FLOW.CFM},0`,filterPressure:'mmH2O',filterText:`0,0\n1,${100/PRESSURE.mmH2O}`});close(inCfm.roots[0].q,calculate(base).roots[0].q);
assert.throws(()=>calculate({...base,speed:''}));
const limited=calculate({...base,method:'interpolation',filterText:'0,0\n0.1,1'});assert.equal(limited.roots.length,0);
console.log('Passed: parsing, duplicates, units, face velocity, fitting, intersections, tangent/multiple roots, fan array/speed, range limits.');
const {advancedResistance}=await import('./calc.mjs');
const settings={...base,width:'500',height:'200',filterFlow:'m/s',filterText:'0,0\n0.5,5\n1,14\n2,44',resistanceType:'planar',density:'1.2',viscosity:'0.000018',lengthScale:'1',depth:'10'};
let ab=advancedResistance(settings);close(ab.c1,6);close(ab.c2,8);close(ab.A,2*6/.000018);close(ab.B,2*8/1.2);close(ab.rmse,0);
// Back-substitute the actual FloTHERM law at every measured velocity.
for(const {v,p} of ab.rows.filter(p=>p.v>0)){const Re=ab.rho*v*ab.L/ab.mu;close(.5*ab.rho*v*v*(ab.A/Re+ab.B),p);}
const vol=advancedResistance({...settings,resistanceType:'volume'});close(vol.A,ab.A/.01);close(vol.B,ab.B/.01);
for(const {v,p} of vol.rows.filter(p=>p.v>0)){const Re=vol.rho*v*vol.L/vol.mu;close(vol.d*.5*vol.rho*v*v*(vol.A/Re+vol.B),p);}
const rescaled=advancedResistance({...settings,lengthScale:'0.01'});close(rescaled.A,ab.A*.01);close(rescaled.B,ab.B);
const cfmPoints=ab.rows.map(({v,p})=>`${v*ab.area/FLOW.CFM},${p/PRESSURE.mmH2O}`).join('\n');
const inOtherUnits=advancedResistance({...settings,filterFlow:'CFM',filterPressure:'mmH2O',filterText:cfmPoints});close(inOtherUnits.A,ab.A);close(inOtherUnits.B,ab.B);
const linear=advancedResistance({...settings,filterText:'0,0\n1,6\n2,12'});close(linear.c1,6);close(linear.c2,0);
const quad=advancedResistance({...settings,filterText:'0,0\n1,8\n2,32'});close(quad.c1,0);close(quad.c2,8);
const bounded=advancedResistance({...settings,filterText:'0,0\n1,10\n2,12'});assert.equal(bounded.constrained,true);assert.ok(bounded.c1>=0&&bounded.c2>=0);
assert.throws(()=>advancedResistance({...settings,filterText:'0,0\n1,10'}));assert.throws(()=>advancedResistance({...settings,viscosity:''}));assert.throws(()=>advancedResistance({...settings,resistanceType:'volume',depth:'0'}));
close(advancedResistance({...settings,extra:'500',dirty:'4'}).A,ab.A);
console.log('Passed: Advanced A/B back-substitution, volume thickness, length scale, flow/pressure conversions, pure terms, nonnegative fit, invalid input, source isolation.');
